apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-paradox
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/vfarcic/devops-paradox.git
    targetRevision: HEAD
    helm:
      values: |
        image:
          tag: latest
        ingress:
          host: devopsparadox.com
      version: v3
  destination:
    namespace: production
    server: devops-paradox.192.168.99.125.xip.io
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
